//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovikZoopark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public Nullable<int> idExkursion { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> valueMan { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<double> itog { get; set; }
        public Nullable<bool> isEnd { get; set; }
    
        public virtual Exkursion Exkursion { get; set; }
        public virtual User User { get; set; }
    }
}
