//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovikZoopark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exkursion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exkursion()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string info { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> maxMan { get; set; }
        public Nullable<bool> isLike { get; set; }
        public Nullable<double> skidka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
